# Generated by Django 3.2.13 on 2022-05-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField()),
                ('title_translit', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('views', models.IntegerField()),
                ('favorites', models.BooleanField(verbose_name=True)),
                ('mark', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
